// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6R3IF8nuDRZJcm9j6V-fg2VjV7-Bh0no',
    appId: '1:671889905357:web:2d990942c63732feee3b84',
    messagingSenderId: '671889905357',
    projectId: 'consumer-price-tracking',
    authDomain: 'consumer-price-tracking.firebaseapp.com',
    storageBucket: 'consumer-price-tracking.appspot.com',
    measurementId: 'G-F5EGRZ137C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqrDTRWTbFJV-SOpmltKRHdWKQEx25c7I',
    appId: '1:671889905357:android:8c7ebb75106fc743ee3b84',
    messagingSenderId: '671889905357',
    projectId: 'consumer-price-tracking',
    storageBucket: 'consumer-price-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDikliNQ52nA1QrM8N71xYFANu3XkyD3dE',
    appId: '1:671889905357:ios:84b4fa214a09b269ee3b84',
    messagingSenderId: '671889905357',
    projectId: 'consumer-price-tracking',
    storageBucket: 'consumer-price-tracking.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDikliNQ52nA1QrM8N71xYFANu3XkyD3dE',
    appId: '1:671889905357:ios:84b4fa214a09b269ee3b84',
    messagingSenderId: '671889905357',
    projectId: 'consumer-price-tracking',
    storageBucket: 'consumer-price-tracking.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6R3IF8nuDRZJcm9j6V-fg2VjV7-Bh0no',
    appId: '1:671889905357:web:2b2b837268925586ee3b84',
    messagingSenderId: '671889905357',
    projectId: 'consumer-price-tracking',
    authDomain: 'consumer-price-tracking.firebaseapp.com',
    storageBucket: 'consumer-price-tracking.appspot.com',
    measurementId: 'G-WPJW4S0B14',
  );
}